#!/bin/sh

case $BUTTON in
	1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd,%cpu --sort=-%cpu | awk '{usage[$1]+= $2} END {for (proc in usage) {printf("%-20s %s%%\n",proc,usage[proc])}}' | sort -rnk 2 | head -n 10)\\n(100% per core)" ;;
	2) setsid -f "$TERMINAL" -e btop ;;
	3) notify-send "🖥 CPU module " "\- Shows CPU temperature.
- Click to show intensive processes.
- Middle click to open btop." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

top -b -n1 | grep "%Cpu(s)" | awk '{printf "🖥%.2f%%\n", 100-$8}'
