#!/bin/sh

case $BUTTON in
	1) notify-send "🧠 Memory hogs" "$(ps axch -o cmd,%mem --sort=-%mem | awk '{if ($2 ~ /^[0-9]/) {process[$1]+=$2;} else {process[$0]+=0}} END {for (i in process) { printf("%-40s %s%%\n",i,process[i]);}}' | sort -k2rn | head -n 10)" ;;
	2) setsid -f "$TERMINAL" -e btop ;;
	3) notify-send "🧠 内存模块" "\- 查看内存使用率和总量.
- 左键点击查看内存占用情况.
- 中键点击打开btop." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

free | awk 'NR==2{printf "🧠%.2f%%\n", $3/$2*100}'
