#!/bin/sh

case $BUTTON in
	3) notify-send "🌐 网络流量模块" "\- 查看实时网络流量
- 🔼: 下行流量
- 🔽: 上行流量" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

update() {
    sum=0
    for arg; do
        read -r i < "$arg"
        sum=$(( sum + i ))
    done
    cache=${XDG_CACHE_HOME:-$HOME/.cache}/${1##*/}
    [ -f "$cache" ] && read -r old < "$cache" || old=0
    printf %d\\n "$sum" > "$cache"
    printf %d\\n $(( sum - old ))
}

RX=$(update /sys/class/net/[ew]*/statistics/rx_bytes)
TX=$(update /sys/class/net/[ew]*/statistics/tx_bytes)

# 换算单位
if [[ $RX -lt 102400 ]];then
    # 如果接收速率小于100KB/s，忽略输出
    RX=""
elif [[ $RX -lt 1048576 ]];then
    # 否则如果接收速率大于等于100KB/s并且小于1MB/s，则单位为KB/s
    RX=$(echo $RX | awk '{printf "%.2f", $1/1024} END {print "KB/s"}') 
else
    # 否则如果接收速率大于等于1MB/s，则单位为MB/s
    RX=$(echo $RX | awk '{printf "%.2f", $1/1048576} END {print "MB/s"}') 
fi

# 换算单位
if [[ $TX -lt 102400 ]];then
    # 如果发送速率小于100KB/s，忽略输出
    TX=""
elif [[ $TX -lt 1048576 ]];then
    # 否则如果发送速率大于等于100KB/s并且小于1MB/s，则单位为KB/s
    TX=$(echo $TX | awk '{printf "%.2f", $1/1024} END {print "KB/s"}') 
else
    # 否则如果发送速率大于等于1MB/s，则单位为MB/s
    TX=$(echo $TX | awk '{printf "%.2f", $1/1048576} END {print "MB/s"}') 
fi

if [[ ! -z $RX ]];then
    printf " 🔽:%7s" $RX
fi
if [[ ! -z $TX ]];then
    printf " 🔼:%7s" $TX
fi
