#!/bin/bash
brightnessctl s $@
brightness=$(brightnessctl i -m | awk -F ',' '{print $4}')
notify-send \
  -e -h string:x-canonical-private-synchronous:osd \
  " $brightness" \
  -h int:value:"$brightness"
