#!/bin/bash
# Set image folder
image_folder="$1"

# Set image change interval
interval="$2"

# Valid param
if [[ $# -ne 2 ]]; then
	echo "Usage: $0 <image_folder> <interval_seconds>"
	exit 1
fi
if [[ ! -d "$image_folder" ]]; then
	echo "The specified image folder '$image_folder' does not exist"
	exit 1
fi

# Set swww animation env
export SWWW_TRANSITION=any
export SWWW_TRANSITION_STEP=90
export SWWW_TRANSITION_FPS=60

while true; do
	# Select random wallpaper and create color scheme
	wal -qst --backend colorz -i ~/Pictures/wallpapers

	# Load current pywal color scheme
	source "$HOME/.cache/wal/colors.sh"

	# Check swww is running
	if ! swww query >/dev/null; then
		exit 1
	fi

	# Change wallpaper
	swww img $wallpaper

	# wait time
	sleep "$interval"
done
