#!/bin/bash
image_url="https://bing.biturl.top/?resolution=3840&format=image&index=random&mkt=random"
image_path="$HOME/.cache/wallpaper.jpg"

# Download wallpaper
curl -sL --connect-timeout 10 -m 30 -o "$image_path" "$image_url"

matugen image $image_path
