#!/bin/bash
threshhold_green=0
threshhold_yellow=25
threshhold_red=100

function json() {
	jq --unbuffered --null-input --compact-output \
		--arg text "$1" \
		--arg alt "$2" \
		--arg tooltip "$3" \
		--arg class "$4" \
		'{"text": $text, "alt": $alt, "tooltip": $tooltip, "class": $class}'
}

# Calculate available updates pacman and aur (with paru)
pacman_updates=$(checkupdates 2>/dev/null)
pacman_updates_count=$(echo "$pacman_updates" | grep -vc ^\$)
# if ! updates_arch=$(checkupdates 2> /dev/null | wc -l ); then
#     updates_arch=0
# fi

if ! updates_aur=$(paru -Qua | wc -l); then
	updates_aur=0
fi

updates_count=$(("$pacman_updates_count" + "$updates_aur"))
updates=""
if [ "$pacman_updates_count" -gt 0 ]; then
	updates+=$(checkupdates)
fi

# Testing

# Overwrite updates with numbers for testing
# updates=101

# test JSON output
# printf '{"text": "0", "alt": "0", "tooltip": "0 Updates", "class": "red"}'
# exit

# Output in JSON format for Waybar Module custom-updates

css_class="green"

if [ "$updates_count" -gt $threshhold_yellow ]; then
	css_class="yellow"
fi

if [ "$updates_count" -gt $threshhold_red ]; then
	css_class="red"
fi

if [ "$updates_count" -le $threshhold_green ]; then
	css_class="green"
fi
json "$updates_count" "$updates_count" "$updates" "$css_class"
