#!/bin/bash
interval="$1"
image_url="https://bing.biturl.top/?resolution=3840&format=image&index=random&mkt=random"
image_path="$HOME/.cache/wallpaper.jpg"

update_wal() {
	# Download wallpaper
	curl -sL -o $image_path $image_url

	# Set swww animation env
	export SWWW_TRANSITION=any
	export SWWW_TRANSITION_STEP=90
	export SWWW_TRANSITION_FPS=60

	# Create color scheme from wallpaper
  rm $HOME/.cache/wal/schemes/*__cache_wallpaper_*.json
	wal -qst -i $image_path

	# Load current pywal color scheme
	source "$HOME/.cache/wal/colors.sh"

	# Update dunst
	dunstrc="$HOME/.config/dunst/dunstrc"
	dunstrc_old="$HOME/.config/dunst/dunstrc.old"
	cp $dunstrc $dunstrc_old
	sed -i "/@color11/{s//$color11/g}" $dunstrc
	systemctl --user restart dunst
	mv -f $dunstrc_old $dunstrc

	if swww query >/dev/null; then
		swww img $wallpaper
	fi
}

if [ -n "$interval" ]; then
	while true; do
		update_wal
		sleep "$interval"
	done
else
	update_wal
fi
